name: mairror_ultimate
description: Mirror Ultimate - Engineering Perfection Build
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # المكتبات الأساسية (The Core)
  http: ^1.1.0
  provider: ^6.1.1
  
  # أدوات الإدراك (AI & Camera)
  camera: ^0.10.5+9
  google_ml_kit: ^0.17.0
  
  # أدوات التواصل (Speech & Audio)
  speech_to_text: ^6.6.2
  flutter_tts: ^3.8.5
  
  # نظام الملفات والأمان (Security & Files)
  path_provider: ^2.1.2
  file_picker: ^6.1.2
  share_plus: ^7.2.2
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  
  # ركن الاستراتيجية (Logic & Games)
  chess: ^0.8.1

flutter:
  uses-material-design: true
