name: mairror_ultimate
description: Mirror Ultimate AI Project
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # هنشيل أرقام النسخ الدقيقة ونخلي فلاتر يختار الأنسب
  provider: any
  camera: any
  google_ml_kit: any
  speech_to_text: any
  flutter_tts: any
  share_plus: any
  file_picker: any
  path_provider: any
  url_launcher: any
  flutter_secure_storage: any
  encrypt: any
  chess: any

flutter:
  uses-material-design: true
