name: mairror_ultimate
description: Mirror Ultimate 2026 - The Final Vision
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.6.3
  camera: ^0.10.3
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  pdf: ^3.10.3
  printing: ^5.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/stories/
